[build]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[alias]
t = "test --workspace"
c = "clippy --workspace -- -D warnings"
b = "bench --workspace"
